BASE_URL = "https://uk.hotels.com/kes/graphql"
COUNTRY_URL = "https://lookup.hotels.com/egta/suggest/v1.4/json"
CITY_URL = "https://lookup.hotels.com/egta/suggest/v1.4/json"

HEADERS = {
    "authority": "uk.hotels.com",
    "pragma": "no-cache",
    "cache-control": "no-cache",
    "sec-ch-ua": '"Google Chrome";v="93", " Not;A Brand";v="99", "Chromium";v="93"',
    "x-locale": "en_GB",
    "dnt": "1",
    "x-platform": "web,desktop",
    "x-channel": "WEB_DESKTOP",
    "x-authentication-state": "anonymous",
    "x-customer-id": "",
    "sec-ch-ua-platform": '"Windows"',
    "x-client-version": "1.1.2235",
    "sec-ch-ua-mobile": "?0",
    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36",
    "accept": "*/*",
    "content-type": "application/json",
    "x-subscriber": "unknown",
    "x-currency": None,
    "x-brand-id": "hotels.com",
    "x-client-id": "kes",
    "x-pos": "HCOM_UK",
    "origin": "https://uk.hotels.com",
    "sec-fetch-site": "same-origin",
    "sec-fetch-mode": "cors",
    "sec-fetch-dest": "empty",
    "referer": "https://uk.hotels.com/",
    "accept-language": "en-US,en;q=0.9,pl;q=0.8",
}

SEARCH_VARIABLES = {
    "sqmState": {
        "destination": {
            "id": None,
            "value": None,
            "type": None,
            "latitude": None,
            "longitude": None,
        },
        "checkIn": None,
        "checkOut": None,
        "rooms": 1,
        "adults": {"0": 1},
        "kids": {"0": []},
    },
    "filterState": {
        "accessibility": [],
        "accommodationType": [],
        "amenities": [],
        "applied": False,
        "brands": [],
        "facilities": [],
        "guestRating": {},
        "landmarks": [],
        "name": {"id": None, "value": ""},
        "neighbourhood": [],
        "paymentPreference": [],
        "popular": [],
        "price": {"multiplier": 1},
        "sortLandmarkId": "",
        "sortOrder": "PRICE",
        "starRating": [],
        "themesAndTypes": [],
        "types": [],
        "vrFilterClicked": False,
        "welcomeRewards": [],
    },
    "pageName": "srp",
    "points": False,
    "pagination": {"pn": None, "pg": 1, "startIndex": None},
}

LISTING_VARIABLES = {
    "sqmState": {
        "destination": {"id": None, "value": "None", "type": "None", "shortName": ""},
        "checkIn": None,
        "checkOut": None,
        "rooms": 1,
        "adults": {"0": 1},
        "kids": {"0": []},
    },
    "filterState": {
        "accessibility": [],
        "accommodationType": [],
        "amenities": [],
        "applied": False,
        "brands": [],
        "facilities": [],
        "guestRating": {"min": None, "max": None},
        "landmarks": [],
        "name": {"id": None, "value": ""},
        "neighbourhood": [],
        "paymentPreference": [],
        "popular": [],
        "price": {"min": None, "max": None, "multiplier": 1, "defaultMax": None},
        "sortLandmarkId": "",
        "sortOrder": "",
        "starRating": [],
        "themesAndTypes": [],
        "types": [],
        "vrFilterClicked": False,
        "welcomeRewards": [],
    },
    "sbgState": {"rooms": 0, "kids": {}, "adults": {}},
    "rateplanId": "",
    "pageName": "pdp",
    "points": False,
}

CITY_PARAMS = {
    "boostConfig": "config-boost-champion",
    "resolutionConfig": "config-resolve-2",
    "current-location-search": "true",
    "providerInfoTypes": "LOCAL,MULTISOURCE,GDS,TPI",
    "locale": "en_US",
    "jsonpCallback": "srsResolve",
}

COUNTRY_PARAMS = {
    "boostConfig": "config-boost-champion",
    "excludeLpa": "false",
    "providerInfoTypes": "LOCAL,MULTISOURCE,GDS,TPI",
    "locale": "en_GB",
    "experiment": "",
    "groupedResults": "false",
    "maxResults": "6",
    "twoLineDisplay": "true",
    "callback": "srsSuggest",
}